## Play with tensors
References:
* https://www.tensorflow.org/versions/r0.10/get_started/basic_usage
* http://stackoverflow.com/questions/39054414/tensorflow-using-tf-slice-to-split-the-input
* https://www.tensorflow.org/api_guides/python/control_flow_ops
* https://www.quora.com/How-does-the-tf-Print-statement-work-for-TensorFlow
* https://www.tensorflow.org/api_guides/python/array_ops#Slicing_and_Joining
* https://www.tensorflow.org/api_docs/python/tf/scatter_nd
* https://www.tensorflow.org/api_docs/python/tf/gather_nd
* http://stackoverflow.com/questions/39157723/how-to-do-slice-assignment-in-tensorflow
* http://stackoverflow.com/questions/35769944/manipulating-matrix-elements-in-tensorflow
* https://petewarden.com/
* http://learningtensorflow.com/lesson6/

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import scipy.misc
import numpy as np

# This is just important on my machine that has 2 Gpus (Where one is not supported by Tensorflow)
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [11]:
# Create a placeholder for images
in_image = tf.placeholder(tf.float32, shape=[256, 256, 3], name="image_in_test")

# Matrix definition
matrix1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = tf.constant([[1,0,1],[2,2,2],[3,3,3]])

# Matrix multiplication
product = tf.matmul(matrix1, matrix2)
tf.Print(product,[product],message='Tensor product evaluated')

# Get slice from matrix 1 from 0,0 selectring 2 rows and 3 collumns
matrix1_slice = tf.slice(matrix1, [0, 0], [2, 3])

# TODO (Scatter, Gather)...
# Gather allow you to sample a tensor from various indexes
index = tf.constant([[0, 0], [1, 1]])
params = tf.constant([[1, 2], [3, 4]])
out_gather = tf.gather_nd(params, index)

# Do some image operations
distorted_image_b = tf.image.random_brightness(in_image, max_delta=63)
distorted_image_s = tf.image.random_saturation(in_image, lower=0.5, upper=1.5)
distorted_image_h = tf.image.random_hue(in_image, max_delta=0.2)
distorted_image_c = tf.image.random_contrast(in_image, lower=0.2, upper=1.8)
distorted_image_f = tf.image.flip_left_right(in_image)
distorted_image_rand_crop = tf.image.central_crop(in_image, central_fraction = 0.5)
# Crop upper part of tensor (-130 on numpy)
distorted_image_crop = tf.slice(in_image, [100,0,0], [156, 256, 3])
# Crop bottom part (Front of car)
distorted_image_crop = tf.slice(distorted_image_crop, [0, 0, 0], [120, 256, 3])

In [12]:
# Build graph
sess = tf.InteractiveSession()

In [13]:
result = sess.run(product)
print(result)

[[14 13 14]
 [32 28 32]
 [50 43 50]]


In [14]:
result = sess.run(matrix1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
result = sess.run(matrix1_slice)
print(result)

[[1 2 3]
 [4 5 6]]


In [21]:
result = sess.run(params)
print('Input')
print(result)
result = sess.run(out_gather)
print('Gather_nd Result:',result)

Input
[[1 2]
 [3 4]]
Gather_nd Result: [1 4]


### Play with images

In [ ]:
img = scipy.misc.imread('2.png', mode='RGB')
img = np.array(img) / 255.0
img = img.astype(np.float)

img_result = sess.run(distorted_image_b, feed_dict={in_image: img})
plt.imshow(img)
plt.show()

plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_s, feed_dict={in_image: img})
plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_h, feed_dict={in_image: img})
plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_c, feed_dict={in_image: img})
plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_f, feed_dict={in_image: img})
plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_rand_crop, feed_dict={in_image: img})
print('Random crop', img_result.shape)
plt.imshow(img_result)
plt.show()

img_result = sess.run(distorted_image_crop, feed_dict={in_image: img})
print('Crop of horizon and car front:',img_result.shape)
plt.imshow(img_result)
plt.show()