## PyTorch first tutorial

Pytorch can be considered as a GPU extension to numpy, also it serves as a deep learning research library, where doing experiments are easier than Tensorflow.

This tutorial will show the following basics:
* Tensor creation
* Acessing tensor elements (also range)
* Moving to the GPU
* Converting data from Numpy to PyTorch and vice-versa
* Autograd

References:

* http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
* http://pytorch.org/tutorials/beginner/pytorch_with_examples.html
* https://github.com/jcjohnson/pytorch-examples
* http://blog.gaurav.im/2017/04/24/a-gentle-intro-to-pytorch/
* http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [1]:
import numpy as np
import torch
from torch.autograd import Variable

dtype = torch.FloatTensor
# dtype = torch.cuda.FloatTensor # Uncomment this to run on GPU

### Some basic matrix manipulation

In [2]:
# Create a 2x3 matrix (2d Tensor)
a = torch.rand(2, 3)
b = torch.rand(2, 3)
c = (a + b) * 2
# Print contents
print(a)
print(b)
print(c)
print
# Print it's shape
print(a.size())


 0.2115  0.1716  0.8654
 0.0135  0.6668  0.9775
[torch.FloatTensor of size 2x3]


 0.0938  0.8411  0.6898
 0.3097  0.2234  0.8247
[torch.FloatTensor of size 2x3]


 0.6106  2.0254  3.1104
 0.6464  1.7804  3.6045
[torch.FloatTensor of size 2x3]

torch.Size([2, 3])


### Tensor range selection/assign and Numpy Pytorch conversion

In [3]:
# Get second collumn of a
print(a[:, 1])

# Set all elements of first collumn to 7 (Try this on tensorflow)
a[:, 0] = 7
print(a)

# Get some particular element (first row second collumn)
print(a[0,1])

# Create a variable on numpy and convert to torch
d_npy = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Numpy matrix shape:',d_npy.shape)
print(d_npy)
# Convert from numpy to torch
d_torch = torch.from_numpy(d_npy)

# Get a range
range_d_torch = d_torch[1:None, 1:3]
print(range_d_torch)

# Convert to numpy array
d_npy_res = range_d_torch.numpy()
print(d_npy_res.shape)
print(d_npy_res)


 0.1716
 0.6668
[torch.FloatTensor of size 2]


 7.0000  0.1716  0.8654
 7.0000  0.6668  0.9775
[torch.FloatTensor of size 2x3]

0.1716495156288147
Numpy matrix shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 5  6
 8  9
[torch.LongTensor of size 2x2]

(2, 2)
[[5 6]
 [8 9]]


### Do some stuff on the GPU

In [4]:
if torch.cuda.is_available():
    # Bring torch tensors to gpu
    a = a.cuda()
    b = b.cuda()
    c = (a + b) * 2
    print(c)


 14.1877   2.0254   3.1104
 14.6193   1.7804   3.6045
[torch.cuda.FloatTensor of size 2x3 (GPU 0)]



### Autograd
PyTorch provides automatic diferentiation to all it's operations on tensors this section will show how it works.
Actually on real cases you just need to define the forward pass of your network.

In [5]:
a = Variable(torch.ones(2, 2), requires_grad=True)
b = Variable(torch.ones(2, 2), requires_grad=True) * 2
print(a)

# Some function
y = a + b
out = y.mean()

print(out)

out.backward()
print(a.grad)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

Variable containing:
 3
[torch.FloatTensor of size 1]

Variable containing:
 0.2500  0.2500
 0.2500  0.2500
[torch.FloatTensor of size 2x2]

